### ISSUE TITLE
Support PHP

### ISSUE THREAD

**Issue by craigharman** [tzachov/vscode-todo-list#13]
Can you add support for PHP?

**Comment by tzachov** [comment]
If you're using single-line comments like `// TODO: lorem ipsum` then you can add `php` extension to `include` setting:
```
**/*.{ts,js,php}
```

Let me know if this is sufficient and I'll set it as default value on the next version.

**Comment by craigharman** [comment]
That works beautifully thank you! One suggestion would be to also add the vendor folder to the exclude list: **/vendor/*
