### ISSUE TITLE
Match without the colon

### ISSUE THREAD

**Issue by t413** [tzachov/vscode-todo-list#18]
I've created an expression to match TODO's, etc, without using a colon (`TODO:`)

```
(?:\/\/|\/\*)[ ]?([A-Z]+)(?: |\:|\(([A-Za-z\/\d ]+)\)\:)[ ]?(.*)
```

While it works and now highlights my TODOs it seems the scanning engine doesn't recognize them. Am I missing something? TODOs without a colon aren't that unusual.

**Comment by tzachov** [comment]
I'll look into it

**Comment by tzachov** [comment]
Looks like it's working after restarting VSCode.

The panel doesn't refresh when expression is changed. I'll fix it on the next version.

Thanks.
