### ISSUE TITLE
Can't create GitHub Issue

### ISSUE THREAD

**Issue by codeThaGlobe** [tzachov/vscode-todo-list#31]
First of all, thanks for an overall great extension!

The one issue I am having is creating a GitHub issue.
I followed the instruction but nothing happens.

Tried creating a personal access token in GitHub and entering it in the GitHub Auth setting.

Any advice?
Thanks in advance!

**Comment by tzachov** [comment]
The `GitHub Auth` setting is not an access token, it's only there so you can clear it.

Please note that this feature will only work if you have permission to create issues on the current repository.

Please follow the next steps:
1. Make sure you have a git config file (`<repositoryRoot>/.git/config`)
2. Make sure remote origin is configured:
```
[remote "origin"]
	url = https://github.com/<...>
```
3. Clear `GitHub Auth` setting
4. Run `Create GitHub Issue` again (enter username and password when prompted)

If nothing happens, you could try using `curl`/`fiddler`/`postman` to see the response from GitHub's API:
1. Simply send a POST request to `https://api.github.com/repos/<username>/<repository>/issues`
2. Body should include `title` and `body`
3. Add `Authorization` header : `Authorization: Bearer <access_token>` (or `Basic` with base64-encoded `<username>:<password>`
4. Finally, add a `user-agent` header: `User-Agent: fake user agent`

**Comment by tzachov** [comment]
@codeThaGlobe please let me know if you managed to create GitHub issue

**Comment by codeThaGlobe** [comment]
Thanks for following up! Great support! 👍 

I ended up using a different plugin though.
All the best.
