### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by VinnieCool** [tzachov/vscode-todo-list#32]
- Issue Type: `Performance`
- Extension Name: `todo-list`
- Extension Version: `1.5.1`
- OS Version: `Windows_NT ia32 10.0.18965` (emulated x86, actual cpu ARM64)
- VSCode version: `1.38.1`

[TzachOvadia.todo-list-unresponsive.cpuprofile.txt](https://github.com/tzachov/vscode-todo-list/files/3635328/TzachOvadia.todo-list-unresponsive.cpuprofile.txt)
`
Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by tzach-chase** [comment]
Hi @VinnieCool 
I couldn't reproduce this issue but I'll make some changes that might help.

**Comment by tzachov** [comment]
Hi @VinnieCool 
I couldn't reproduce this issue but I'll make some changes that might help.
