### ISSUE TITLE
How do I view the list?

### ISSUE THREAD

**Issue by mmcintyre123** [tzachov/vscode-todo-list#34]
I see the extension recognizing my todo comments, but I can't see how to call up a list of all todos in the project.  

![image](https://user-images.githubusercontent.com/12388285/69466388-e85ad380-0d51-11ea-9a15-ae4a6253816d.png)

**Comment by mmcintyre123** [comment]
Never mind - I found it - called "Action Comments" in the file explorer.

![image](https://user-images.githubusercontent.com/12388285/69466821-9c109300-0d53-11ea-9bb6-ff4386805505.png)

![image](https://user-images.githubusercontent.com/12388285/69466903-e42fb580-0d53-11ea-92d8-f1fd8d66b87f.png)

**Comment by noodles** [comment]
You should add this detail to your instructions page or at least pin this issue so new users can see it.
It is not immediately obvious where the action comments pane is located.

**Comment by mmcintyre123** [comment]
> You should add this detail to your instructions page or at least pin this issue so new users can see it. It is not immediately obvious where the action comments pane is located.

@tzachov
