### ISSUE TITLE
enable/disabled flag in the settings for command palette and context menu

### ISSUE THREAD

**Issue by pabgom** [tzachov/vscode-todo-list#35]
Hello,
Could be possible add some flags in the setting disable in the context menu the options we don't need it?

**Comment by tzachov** [comment]
Do you mean `Create Trello Card` and `Send using Gmail` menu? Yes, I think I'll even make it disabled by default.

**Comment by pabgom** [comment]
Yes I am talking about Create Trello Card and Send using Gmail. This question is because change the normal behavior in the IDE and there isn't a way to disable this changes.
