### ISSUE TITLE
Running the contributed command: 'extension.convertToComment' failed.

### ISSUE THREAD

**Issue by adamprocter** [tzachov/vscode-todo-list#4]
I get this error when trying to use the command palette on macOS

**Comment by tzachov** [comment]
Sorry for that, I forgot to remove it. This command will be used in a future release.

What would you expect this command to do?

**Comment by adamprocter** [comment]
I opened the command palette And typed TODO and then got that error I thought it was a way to build the comment ?

**Comment by adamprocter** [comment]
Ah ha this is working for .js files sorry I was trying to use this on .vue files
